name: ARVEXA_Factory
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          pip install --upgrade buildozer
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev libtinfo6
          # Fabrikanın SDK'yı kurması için gerekli izinleri veriyoruz
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROIDSDK/cmdline-tools/latest/bin
          buildozer --verbose android debug
