name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Install System Dependencies & Python
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
              git wget curl unzip libltdl-dev \
              build-essential libssl-dev libffi-dev \
              python3-dev python3-pip python3-setuptools libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev \
              openjdk-17-jdk autoconf libtool pkg-config \
              libncurses5:i386 libstdc++6:i386 zlib1g:i386

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user cython==0.29.36 buildozer

      - name: Run Buildozer
        working-directory: apps/pusula
        run: |
          export PATH=$PATH:~/.local/bin
          rm -rf .buildozer bin
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: apps/pusula/bin/*.apk
          if-no-files-found: error
