name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        working-directory: apps/pusula
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: apps/pusula/bin/*.apk
